---
openapi: 3.0.0
info:
  title: Swagger Vulcan
  description: "C'est une api qui à pour but de créer un site d'Hotel avec  tout un backoffice qui permet d'administrer le site via un WYSIWYG \n"
  contact:
    email: theo.colombel@le-campus-numerique.fr
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/THEOCOLOMBEL/api-vulcan/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Rooms
  description: Everything about the hotel rooms
- name: BackOffice
  description: Access and modifiy every thing on the landing page
paths:
  /room/{id}/update:
    put:
      tags:
      - BackOffice
      summary: Update an existing room
      operationId: updatePet
      requestBody:
        $ref: '#/components/requestBodies/Room'
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception
      security:
      - petstore_auth:
        - write:pets
        - read:pets
components: 
  schemas:
    Room:
      type: object
      properties:
        id:
          type: integer
        name: 
          type: string
        image:
          type: string
        description:
          type: string
        price:
          type: integer
        roomType:
          type: string
        personPerRoom:
          type: integer
    News:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        image:
          type: string
        description:
          type: string
        date:
          type: string
    Advantages:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        icon:
          type: string
        description:
          type: string
    Reviews:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        description:
          type: string
        rating:
          type: integer
        username:
          type: string
        userAvatar:
          type: string
    Banner:
      type: object
      properties:
        id:
          type: integer
        image:
          type: string
    FooterLinks:
      type: object
      properties:
        id:
          type: integer
        links:
          type: array
    Video:
      type: object
      properties:
        id:
          type: integer
        link:
          type: string
  requestBodies:
    Room:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Room'
      required: true
    News:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/News'
      required: true
    Banner:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Banner'
      required: true
    Advantages:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Advantages'
      required: true
    Reviews:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Reviews'
      required: true
    FooterLinks:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FooterLinks'
      required: true
    Video:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Video'
      required: true
        
