---
openapi: 3.0.0
info:
  title: Swagger Vulcan
  description: "C'est une api qui à pour but de créer un site d'Hotel avec  tout un backoffice qui permet d'administrer le site via un WYSIWYG \n"
  contact:
    email: theo.colombel@le-campus-numerique.fr
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/THEOCOLOMBEL/api-vulcan/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Rooms
  description: Everything about the hotel rooms
- name: BackOffice
  description: Access and modifiy every thing on the landing page
paths:
  /delete/rooms:
    delete:
      tags:
      - BackOffice
      summary: Delete an all rooms
      requestBody:
        $ref: '#/components/requestBodies/Room'
      responses:
        "200":
          description: Rooms delete
        "404":
          description: Room not found
  /delete/room/{id}:
    delete:
      tags:
      - BackOffice
      summary: Delete an existing room
      requestBody:
        $ref: '#/components/requestBodies/Room'
      responses:
        "200":
          description: Room delete
        "400":
          description: Invalid ID supplied
        "404":
          description: Room not found
  /delete/news:
    delete:
      tags:
      - BackOffice
      summary: Delete an all news
      requestBody:
        $ref: '#/components/requestBodies/News'
      responses:
        "200":
          description: News delete
        "404":
          description: News not found
  /delete/news/{id}:
    delete:
      tags:
      - BackOffice
      summary: Delete an existing news
      requestBody:
        $ref: '#/components/requestBodies/News'
      responses:
        "200":
          description: News delete
        "400":
          description: Invalid ID supplied
        "404":
          description: News not found
  /delete/advantages:
    delete:
      tags:
      - BackOffice
      summary: Delete an all advantages
      requestBody:
        $ref: '#/components/requestBodies/Advantages'
      responses:
        "200":
          description: Advantages delete
        "404":
          description: Advantages not found
  /delete/advantages/{id}:
    delete:
      tags:
      - BackOffice
      summary: Delete an existing advantages
      requestBody:
        $ref: '#/components/requestBodies/Advantages'
      responses:
        "200":
          description: Advantages delete
        "400":
          description: Invalid ID supplied
        "404":
          description: Advantages not found
  /delete/reviews:
    delete:
      tags:
      - BackOffice
      summary: Delete an all reviews
      requestBody:
        $ref: '#/components/requestBodies/Reviews'
      responses:
        "200":
          description: Reviews delete
        "404":
          description: Reviews not found
  /delete/reviews/{id}:
    delete:
      tags:
      - BackOffice
      summary: Delete an existing reviews
      requestBody:
        $ref: '#/components/requestBodies/Reviews'
      responses:
        "200":
          description: Reviews delete
        "400":
          description: Invalid ID supplied
        "404":
          description: Reviews not found
  /delete/banner:
    delete:
      tags:
      - BackOffice
      summary: Delete an all banner
      requestBody:
        $ref: '#/components/requestBodies/Banner'
      responses:
        "200":
          description: Banner delete
        "404":
          description: Banner not found
  /delete/banner/{id}:
    delete:
      tags:
      - BackOffice
      summary: Delete an existing banner
      requestBody:
        $ref: '#/components/requestBodies/Banner'
      responses:
        "200":
          description: Banner delete
        "400":
          description: Invalid ID supplied
        "404":
          description: Banner not found
  /delete/footerLinks:
    delete:
      tags:
      - BackOffice
      summary: Delete an all footerLinks
      requestBody:
        $ref: '#/components/requestBodies/FooterLinks'
      responses:
        "200":
          description: FooterLinks delete
        "404":
          description: FooterLinks not found
  /delete/footerLinks/{id}:
    delete:
      tags:
      - BackOffice
      summary: Delete an existing footerLinks
      requestBody:
        $ref: '#/components/requestBodies/FooterLinks'
      responses:
        "200":
          description: FooterLinks delete
        "400":
          description: Invalid ID supplied
        "404":
          description: FooterLinks not found
  /delete/video:
    delete:
      tags:
      - BackOffice
      summary: Delete an all video
      requestBody:
        $ref: '#/components/requestBodies/Video'
      responses:
        "200":
          description: Video delete
        "404":
          description: Video not found
  /delete/video/{id}:
    delete:
      tags:
      - BackOffice
      summary: Delete an existing video
      requestBody:
        $ref: '#/components/requestBodies/Video'
      responses:
        "200":
          description: Video delete
        "400":
          description: Invalid ID supplied
        "404":
          description: Video not found
components: 
  schemas:
    Room:
      type: object
      properties:
        id:
          type: integer
        name: 
          type: string
        image:
          type: string
        description:
          type: string
        price:
          type: integer
        roomType:
          type: string
        personPerRoom:
          type: integer
    News:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        image:
          type: string
        description:
          type: string
        date:
          type: string
    Advantages:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        icon:
          type: string
        description:
          type: string
    Reviews:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        description:
          type: string
        rating:
          type: integer
        username:
          type: string
        userAvatar:
          type: string
    Banner:
      type: object
      properties:
        id:
          type: integer
        image:
          type: string
    FooterLinks:
      type: object
      properties:
        id:
          type: integer
        links:
          type: array
    Video:
      type: object
      properties:
        id:
          type: integer
        link:
          type: string
  requestBodies:
    Room:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Room'
      required: true
    News:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/News'
      required: true
    Banner:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Banner'
      required: true
    Advantages:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Advantages'
      required: true
    Reviews:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Reviews'
      required: true
    FooterLinks:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FooterLinks'
      required: true
    Video:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Video'
      required: true
        
