---
openapi: 3.0.0
info:
  title: Swagger Vulcan
  description: "C'est une api qui à pour but de créer un site d'Hotel avec  tout un backoffice qui permet d'administrer le site via un WYSIWYG \n"
  contact:
    email: theo.colombel@le-campus-numerique.fr
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/THEOCOLOMBEL/api-vulcan/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Rooms
  description: Everything about the hotel rooms
- name: BackOffice
  description: Access and modifiy every thing on the landing page
paths:
  /create/room/{id}:
    post:
      tags:
      - BackOffice
      summary: Create a new room
      requestBody:
        $ref: '#/components/requestBodies/Room'
      responses:
        "200":
          description: Room created
        "400":
          description: Invalid ID supplied
        "404":
          description: Validation exception
  /create/news/{id}:
    post:
      tags:
      - BackOffice
      summary: Create a new news
      requestBody:
        $ref: '#/components/requestBodies/News'
      responses:
        "200":
          description: news created
        "400":
          description: Invalid ID supplied
        "404":
          description: Validation exception
  /create/advantages/{id}:
    post:
      tags:
      - BackOffice
      summary: Create a new advantage
      requestBody:
        $ref: '#/components/requestBodies/Advantages'
      responses:
        "200":
          description: advantage created
        "400":
          description: Invalid ID supplied
        "404":
          description: Validation exception
  /create/reviews/{id}:
    post:
      tags:
      - BackOffice
      summary: Create a new review
      requestBody:
        $ref: '#/components/requestBodies/Reviews'
      responses:
        "200":
          description: review created
        "400":
          description: Invalid ID supplied
        "404":
          description: Validation exception
  /create/banner/{id}:
    post:
      tags:
      - BackOffice
      summary: Create a new banner
      requestBody:
        $ref: '#/components/requestBodies/Banner'
      responses:
        "200":
          description: banner created
        "400":
          description: Invalid ID supplied
        "404":
          description: Validation exception
  /create/footerLinks/{id}:
    post:
      tags:
      - BackOffice
      summary: Create a new footer Link
      requestBody:
        $ref: '#/components/requestBodies/FooterLinks'
      responses:
        "200":
          description: footer Link created
        "400":
          description: Invalid ID supplied
        "404":
          description: Validation exception
  /create/video/{id}:
    post:
      tags:
      - BackOffice
      summary: Create a new video
      requestBody:
        $ref: '#/components/requestBodies/Video'
      responses:
        "200":
          description: video created
        "400":
          description: Invalid ID supplied
        "404":
          description: Validation exception
components: 
  schemas:
    Room:
      type: object
      properties:
        id:
          type: integer
        name: 
          type: string
        image:
          type: string
        description:
          type: string
        price:
          type: integer
        roomType:
          type: string
        personPerRoom:
          type: integer
    News:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        image:
          type: string
        description:
          type: string
        date:
          type: string
    Advantages:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        icon:
          type: string
        description:
          type: string
    Reviews:
      type: object
      properties:
        id:
          type: integer
        title: 
          type: string
        description:
          type: string
        rating:
          type: integer
        username:
          type: string
        userAvatar:
          type: string
    Banner:
      type: object
      properties:
        id:
          type: integer
        image:
          type: string
    FooterLinks:
      type: object
      properties:
        id:
          type: integer
        links:
          type: array
    Video:
      type: object
      properties:
        id:
          type: integer
        link:
          type: string
  requestBodies:
    Room:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Room'
      required: true
    News:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/News'
      required: true
    Banner:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Banner'
      required: true
    Advantages:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Advantages'
      required: true
    Reviews:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Reviews'
      required: true
    FooterLinks:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FooterLinks'
      required: true
    Video:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Video'
      required: true
        
